version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_name  # Altere para o nome do banco de dados que você deseja
      - DB_USER=postgres
      - DB_PASSWORD=db_psswd  # A senha definida no container PostgreSQL
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: some-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_psswd
      - POSTGRES_DB=db_name  # Altere para o nome do banco de dados que você deseja
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
